# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: $(ServiceConnection)
  imageRepository: 'webapidotnetdocker'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      name: ContainerRegistry
      displayName: Obtem URL do ACR
      inputs:
        targetType: 'inline'
        script: 'echo "##vso[task.setvariable variable=containerRegistry;isoutput=true]$(ContainerRegistryUrl)"'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: | 
          latest
          $(tag)
- stage: Deployment
  displayName: Deployment Azure App Service
  dependsOn: Build
  jobs:
  - job: Deployment
    variables:
      containerRegistry: $[stageDependencies.Build.Build.outputs['ContainerRegistry.containerRegistry']]
    displayName: Deployment Azure App Service
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deployment Azure App Service com ACR
      inputs:
        azureSubscription: 'AzureResources'
        appName: 'netdockerexample'
        containers: '$(containerRegistry)/$(imageRepository):$(tag)'